= Getting Started with the Hazelcast .NET Client
// Add required variables
:page-layout: tutorial
:page-product: platform
:page-categories: Get Started
:page-lang: csharp
:page-enterprise:
:page-est-time: 5-10 mins
:description: In this tutorial you will see how to connect with the Hazelcast .NET client and manipulate a map.

== What You'll Learn

{description}

== Before you Begin

Before starting this tutorial, make sure the following prerequisites are met:


* .NET SDK 6.0 or above
* https://hazelcast.com/products/viridian/[Hazelcast Viridian Cloud Account]
* An IDE

== Start a Hazelcast Viridian Cloud Cluster

1. Sign up for a Hazelcast Viridian Cloud account (Free accounts are available).
2. Log in to your Hazelcast Viridian Cloud account and navigate to your https://viridian.hazelcast.com[cluster list].
3. Create a new cluster or start an existing one.

== Setup a Hazelcast Client

1. Use the quick connection guide to download the preconfigured .NET sample client.
2. Follow the instructions on the quick connection guide to start using your cluster.

To understand and use the client, review the https://hazelcast.github.io/hazelcast-csharp-client/versions.html[.NET API documentation] to better understand what is possible.

== Understanding the .NET Client

The following section creates and starts a Hazelcast client with default configuration, before shutting it down at the end.

[source,csharp]
----
using Hazelcast;

namespace Client
{
    internal static class Program
    {
        public static async Task Main(string[] args)
        {
            // Create a client connection            
            var options = new HazelcastOptionsBuilder()
                .With(args) // Pass command line args to the client
                .Build();

            await using var client = await HazelcastClientFactory.StartNewClientAsync(options);

            // take actions
        }
}
----

== Understanding the Hazelcast Map

A Hazelcast Map is a distributed key-value store, similar to C# dictionary. You can store key-value pairs in a Hazelcast Map.

In the following example, we will work with map entries where the keys are ids and the values are defined as an object representing a city.

[source,csharp]
----
using Hazelcast;

namespace Client
{
    internal static class Program
    {
        public static async Task Main(string[] args)
        {
            // Create a client connection
            var options = new HazelcastOptionsBuilder()
                .With(args) // Pass command line args to the client
                .Build();

            await using var client = await HazelcastClientFactory.StartNewClientAsync(options);

            // Create a map on the cluster
            await using var citiesMap = await client.GetMapAsync<int, string>("cities");

            // Add some data
            await citiesMap.PutAsync(1, "London");
            await citiesMap.PutAsync(2, "New York");
            await citiesMap.PutAsync(3, "Tokyo");

            // Output the data
            var entries = citiesMap.GetEntriesAsync();

            foreach (var entry in entries.Result)
            {
                Console.WriteLine($"{entry.Key} -> {entry.Value}");
            }
        }
}
----

Following line returns a map proxy object for the `cities` map:

[source, csharp]
----
            // Create a map on the cluster
            await using var citiesMap = await client.GetMapAsync<int, string>("cities");
----

If `cities` doesn't exist, it will be automatically created. All the clients connected to the same cluster will have access to the same map.

With these lines, client adds data to the `cities` map. The first parameter is the key of the entry, the second one is the value.

[source, csharp]
----
            // Add some data
            await citiesMap.PutAsync(1, "London");
            await citiesMap.PutAsync(2, "New York");
            await citiesMap.PutAsync(3, "Tokyo");
----

Then, we get the data using the `GetEntriesAsync()` method and iterate over the results.

[source, python]
----
            // Output the data
            var entries = citiesMap.GetEntriesAsync();

            foreach (var entry in entries.Result)
            {
                Console.WriteLine($"{entry.Key} -> {entry.Value}");
            }
----

The output of this code is given below:

[source,bash]
----
2 -> New York
1 -> London
3 -> Tokyo
----

NOTE: Ordering of the keys is NOT enforced and results may NOT correspond to entry order.


== Summary

In this tutorial, you learned how to get started with the Hazelcast .NET Client and put data into a distributed map. 

== See Also

There are a lot of things that you can do with the .NET Client. For more, such as how you can query a map with predicates and SQL,
check out our https://github.com/hazelcast/hazelcast-csharp-client[.NET Client repository] and our https://hazelcast.github.io/hazelcast-csharp-client/versions.html[.NET API documentation] to better understand what is possible.

If you have any questions, suggestions, or feedback please do not hesitate to reach out to us via https://slack.hazelcast.com/[Hazelcast Community Slack].
Also, please take a look at https://github.com/hazelcast/hazelcast-csharp-client/issues[the issue list] if you would like to contribute to the client.


